version: '3.8'

services:
  web:
    build: .
    command: gunicorn tmdb_net.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - USE_SQLITE=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,103.90.75.250,kino-bro.ru,www.kino-bro.ru
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - tmdb_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - tmdb_network

networks:
  tmdb_network:
    driver: bridge

volumes:
  postgres_data: 