version: '3.8'

services:
  web:
    build: .
    command: gunicorn tmdb_net.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - USE_SQLITE=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,103.90.75.250,kino-bro.ru,www.kino-bro.ru
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - tmdb_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - tmdb_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secure_password
      PGADMIN_SERVER_DEFAULT_HOST: db
      PGADMIN_SERVER_DEFAULT_PORT: 5432
      PGADMIN_SERVER_DEFAULT_USER: tmdb_user
      PGADMIN_SERVER_DEFAULT_PASSWORD: tmdb_password
      PGADMIN_SERVER_DEFAULT_DATABASE: tmdb_db
      PGADMIN_SERVER_DEFAULT_CONNECT_TIMEOUT: 10
      PGADMIN_SERVER_DEFAULT_SSL_MODE: prefer
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - tmdb_network

networks:
  tmdb_network:
    external: true
    name: tmdb-project_tmdb_network

volumes:
  postgres_data:
  pgadmin_data: 