# Generated by Django 4.2.7 on 2025-03-31 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_tvshow_season_episode_tvshowreview_seasonreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShowWatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_watch', 'Want to Watch'), ('watching', 'Watching'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('dropped', 'Dropped')], max_length=20)),
                ('is_rewatching', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_statuses', to='movies.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvshow_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TV show watch statuses',
                'unique_together': {('user', 'tvshow')},
            },
        ),
        migrations.CreateModel(
            name='MovieWatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_watch', 'Want to Watch'), ('watching', 'Watching'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('dropped', 'Dropped')], max_length=20)),
                ('is_rewatching', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_statuses', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Movie watch statuses',
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
